# permissions for end users to edit cpps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cpp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-demo
    app.kubernetes.io/part-of: kubebuilder-demo
    app.kubernetes.io/managed-by: kustomize
  name: cpp-editor-role
rules:
- apiGroups:
  - ingress.example.com
  resources:
  - cpps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress.example.com
  resources:
  - cpps/status
  verbs:
  - get
