# permissions for end users to view cpps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cpp-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-demo
    app.kubernetes.io/part-of: kubebuilder-demo
    app.kubernetes.io/managed-by: kustomize
  name: cpp-viewer-role
rules:
- apiGroups:
  - ingress.example.com
  resources:
  - cpps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingress.example.com
  resources:
  - cpps/status
  verbs:
  - get
